# -*- coding: utf-8 -*-
"""3 лаб

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqgPTCc1CMJB5zEHn8fGkgahZUWtE1h-
"""

a = int(input())
b = int(input())
if a > b:
  print('sfsfsf')
elif a == b:
  print('dfdf')
else:
  print('pfpfpfp')

def fun(a, b):
  c = a + b
  print(c)
fun(5, 6)

#1 задание
def k(m):
  if m == 1:
    print('январь')
  if m == 2:
    print('февраль')
  if m == 3:
    print('март')
  if m == 4:
    print('апрель')
  if m == 5:
    print('май')
  if m == 6:
    print('июнь')
  if m == 7:
    print('июль')
  if m == 8:
    print('август')
  if m == 9:
    print('сентябрь')
  if m == 10:
    print('октябрь')
  if m == 11:
    print('ноябрь')
  if m == 12:
    print('декабрь')
a = int(input())
k(a)

#2 задание
a = int(input())
if a % 2 == 0:
  print('четное')
else:
  print('нечетное')

#3 задание
def k(n):
  if n > 40:
    print('stonks')
  if n < 40:
    print('not stonks')
n = int(input())
k(n)

#4 задание
def is_year_leap(g):
  if (g % 4 == 0) and ((g % 100 != 0) or (g % 400 == 0)):
    print('True')
  else:
    print('False')
g = int(input())
is_year_leap(g)

#5 задание
def is_prime(n):
  k = 0
  for i in range(2, n - 1):
    if n % i == 0:
      k += 1
  if k <= 0:
    print('True')
  else:
    print('False')
n = int(input())
is_prime(n)

#6 задание
def f(a, b):
  n = 0
  if (a // b > 3.6) or ((b >= (abs((-138/2)**1.3))) and (b <= (abs((-69/28**5.1)*4)))):
    a, b = b, a
  print(a, b)
a = int(input())
b = int(input())
f(a, b)

#7 задание
d = []
d.append(int(input()))
d.append(int(input()))
d.append(int(input()))
d.append(int(input()))
d.append(int(input()))
if len(set(d) == len(d)):
    print("Все уникальные")
else:
    print("Повторяются")
kolotr = sum(num < 0 for num in d)
print("Кол-во отриц = ", kolotr)
kolchet = sum(nums % 2 == 0 for nums in d)
print("Кол-во четных", kolchet)
pr = sum(-256 <= nummm <= 1024 for nummm in d)
print("Кол-во чисел в промежутке = ", pr)

#8 задание
a = int(input())
b = int(input())
c = int(input())
def f(a, b, c):
  n = ((a**2 + b**3)//(c+3))//4
  if n % 2 == 0:
    return True
  else:
    return False
f(a, b, c)